---
alias: bedroom_lights_alarm
description: ""
triggers:
  - trigger: time
    at: "06:45:00"
conditions:
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state:
      - "on"
actions:
  - action: light.turn_on
    metadata: {}
    target:
      entity_id:
        - light.bedroom_bulb_bedside
        - light.lily_bedroom_bulb_window
    data:
      color_temp_kelvin: 3000
      brightness_pct: 1
  - delay:
      hours: 0
      minutes: 30
      seconds: 0
      milliseconds: 0
  - action: light.turn_off
    metadata: {}
    target:
      entity_id:
        - light.bedroom_bulb_bedside
        - light.lily_bedroom_bulb_window
    data: {}
mode: single
