---
alias: Bedroom Lights Alarm
description: ""
triggers:
  - trigger: time
    at: "06:45:00"
conditions:
  - condition: state
    entity_id: binary_sensor.workday_sensor_se
    state:
      - "on"
actions:
  - action: light.turn_on
    metadata: {}
    data:
      color_temp_kelvin: 3000
      brightness_pct: 1
    target:
      entity_id:
        - light.bedroom_bedside_lamp
        - light.lily_bedroom_window_lamp
  - delay:
      hours: 0
      minutes: 30
      seconds: 0
      milliseconds: 0
  - action: light.turn_off
    metadata: {}
    data: {}
    target:
      entity_id:
        - light.bedroom_bedside_lamp
        - light.lily_bedroom_window_lamp
mode: single
