---
alias: Exterior Lights Sunrise
description: ''
triggers:
  - event: sunrise
    offset: '00:10:00'
    trigger: sun
conditions: []
actions:
  - action: light.turn_off
    metadata: {}
    data:
      transition: 60
    target:
      entity_id: light.exterior
mode: single
