---
alias: cinema_start
description: ''
triggers:
  - trigger: state
    entity_id:
      - media_player.plex_for_lg
    to: playing
conditions:
  - condition: sun
    after: sunset
  - condition: template
    value_template: >
      {{ state_attr('media_player.plex_for_lg', 'media_duration') | int(0) > 3600 }}
actions:
  - action: light.turn_off
    metadata: {}
    data:
      transition: 5
    target:
      entity_id:
        - light.living_room_bulb_window
mode: single